FROM node:22-alpine

WORKDIR /app

# Install dependencies dulu (cache layer)
COPY package.json yarn.lock ./
RUN yarn install

# Copy semua file project
COPY . .

# Generate Prisma Client
RUN yarn prisma generate

EXPOSE 3000

CMD ["yarn", "dev"]