name: Deploy Dev

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ke Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /var/www/my-app
            git pull origin dev
            sudo docker compose -f docker-compose.dev.yml down
            sudo docker compose -f docker-compose.dev.yml up -d --build
            sudo docker compose -f docker-compose.dev.yml exec -T app-dev npx prisma migrate deploy
            sudo docker compose -f docker-compose.dev.yml exec -T app-dev npx prisma db push
